JDMallen.AppName/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;
using JDMallen.AppName.ModelDescriptions;

namespace JDMallen.AppName.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            UriParameters = new Collection<ParameterDescription>();
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ParameterDescription"/> collection that describes the URI parameters for the API.
        /// </summary>
        public Collection<ParameterDescription> UriParameters { get; private set; }

        /// <summary>
        /// Gets or sets the documentation for the request.
        /// </summary>
        public string RequestDocumentation { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the request body.
        /// </summary>
        public ModelDescription RequestModelDescription { get; set; }

        /// <summary>
        /// Gets the request body parameter descriptions.
        /// </summary>
        public IList<ParameterDescription> RequestBodyParameters
        {
            get
            {
                return GetParameterDescriptions(RequestModelDescription);
            }
        }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the resource.
        /// </summary>
        public ModelDescription ResourceDescription { get; set; }

        /// <summary>
        /// Gets the resource property descriptions.
        /// </summary>
        public IList<ParameterDescription> ResourceProperties
        {
            get
            {
                return GetParameterDescriptions(ResourceDescription);
            }
        }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }

        private static IList<ParameterDescription> GetParameterDescriptions(ModelDescription modelDescription)
        {
            ComplexTypeModelDescription complexTypeModelDescription = modelDescription as ComplexTypeModelDescription;
            if (complexTypeModelDescription != null)
            {
                return complexTypeModelDescription.Properties;
            }

            CollectionModelDescription collectionModelDescription = modelDescription as CollectionModelDescription;
            if (collectionModelDescription != null)
            {
                complexTypeModelDescription = collectionModelDescription.ElementDescription as ComplexTypeModelDescription;
                if (complexTypeModelDescription != null)
                {
                    return complexTypeModelDescription.Properties;
                }
            }

            return null;
        }
    }
}

JDMallen.AppName/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using JDMallen.AppName.ModelDescriptions;
using JDMallen.AppName.Models;

namespace JDMallen.AppName.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

JDMallen.AppName/Controllers/MasterApiController.cs
using System.Web.Http;
using JDMallen.AppName.Data.IRepos;
using Newtonsoft.Json;

namespace JDMallen.AppName.Controllers
{
    public abstract class MasterApiController : ApiController {
        protected ISessionRepo SessionRepo { get; set; }

        protected MasterApiController(ISessionRepo sessionRepo) {
            SessionRepo = sessionRepo;
        }

        public static string SuperSerialize(object obj) {
            return JsonConvert.SerializeObject(obj, Formatting.Indented);
        }
    }
}

JDMallen.AppName/Controllers/SessionsController.cs
using System.Web.Http;
using JDMallen.AppName.Data.IRepos;
using JDMallen.AppName.Data.Models;

namespace JDMallen.AppName.Controllers {
    public class SessionsController : MasterApiController {

        /// <summary>
        /// Logs in a user, returns a session object that may be stored 
        /// in a cookie or other session management system.
        /// </summary>
        /// <param name="login">Object with "user" and "pwd" params.</param>
        /// <returns></returns>
        public Session Post([FromBody] Login login) {
            return SessionRepo.LogIn(login.user, login.pwd);
        }
        
        /// <summary>
        /// Logs out a user. You may use the username or email in the body.
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        public string Delete(string user) {
            return SessionRepo.LogOut(user);
        }

        public SessionsController(ISessionRepo sessionRepo)
            : base(sessionRepo) {}
    }
}

JDMallen.AppName/Views/Help/Api.cshtml
@using System.Web.Http
@model JDMallen.AppName.Models.HelpPageApiModel

@{
    var description = Model.ApiDescription;
    ViewBag.Title = description.HttpMethod.Method + " " + description.RelativePath;
}

<link type="text/css" href="~/Content/HelpPage.css" rel="stylesheet" />
<div id="body" class="row help-page">
    <section class="featured">
        <div class="content-wrapper">
            <p>
                @Html.ActionLink("Help Page Home", "Index")
            </p>
        </div>
    </section>
</div>
@Html.DisplayForModel()

JDMallen.AppName/Views/Help/DisplayTemplates/ApiGroup.cshtml
@using System.Web.Http
@using System.Web.Http.Controllers
@using System.Web.Http.Description
@using JDMallen.AppName
@model IGrouping<HttpControllerDescriptor, ApiDescription>

@{
    var controllerDocumentation = ViewBag.DocumentationProvider != null ? 
        ViewBag.DocumentationProvider.GetDocumentation(Model.Key) : 
        null;
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h2 id="@Model.Key.ControllerName">@Model.Key.ControllerName</h2>
    </div>
    @if (!String.IsNullOrEmpty(controllerDocumentation)) {
        <div class="panel-body">
            <p>@controllerDocumentation</p>
        </div>
    }
    <table class="table">
        <thead>
            <tr><th style="width: 50%">API</th><th>Description</th></tr>
        </thead>
        <tbody>
            @foreach (var api in Model) {
                <tr>
                    <td class="code"><a href="@Url.Action("Api", "Help", new { apiId = api.GetFriendlyId() })">@api.HttpMethod.Method @api.RelativePath</a></td>
                    <td>
                        @if (api.Documentation != null) {
                            <p>@api.Documentation</p>
                        } else {
                            <p>No documentation available.</p>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

JDMallen.AppName/Views/Help/DisplayTemplates/CollectionModelDescription.cshtml
@using JDMallen.AppName.ModelDescriptions
@model JDMallen.AppName.ModelDescriptions.CollectionModelDescription

@if (Model.ElementDescription is ComplexTypeModelDescription) {
    @Html.DisplayFor(m => m.ElementDescription)
}

JDMallen.AppName/Views/Help/DisplayTemplates/ComplexTypeModelDescription.cshtml
@model JDMallen.AppName.ModelDescriptions.ComplexTypeModelDescription
@Html.DisplayFor(m => m.Properties, "Parameters")

JDMallen.AppName/Views/Help/DisplayTemplates/DictionaryModelDescription.cshtml
@model JDMallen.AppName.ModelDescriptions.DictionaryModelDescription
Dictionary of @Html.DisplayFor(m => Model.KeyModelDescription.ModelType, "ModelDescriptionLink", new { modelDescription = Model.KeyModelDescription }) [key]
and @Html.DisplayFor(m => Model.ValueModelDescription.ModelType, "ModelDescriptionLink", new { modelDescription = Model.ValueModelDescription }) [value]

JDMallen.AppName/Views/Help/DisplayTemplates/EnumTypeModelDescription.cshtml
@using JDMallen.AppName.ModelDescriptions
@model JDMallen.AppName.ModelDescriptions.EnumTypeModelDescription

<p>Possible enumeration values:</p>

<table class="help-page-table">
    <thead>
        <tr><th>Name</th><th>Value</th><th>Description</th></tr>
    </thead>
    <tbody>
        @foreach (EnumValueDescription value in Model.Values)
        {
            <tr>
                <td class="enum-name"><b>@value.Name</b></td>
                <td class="enum-value">
                    <p>@value.Value</p>
                </td>
                <td class="enum-description">
                    <p>@value.Documentation</p>
                </td>
            </tr>
        }
    </tbody>
</table>

JDMallen.AppName/Views/Help/DisplayTemplates/HelpPageApiModel.cshtml
@using System.Web.Http
@using System.Web.Http.Description
@model JDMallen.AppName.Models.HelpPageApiModel

@{
    ApiDescription description = Model.ApiDescription;
}
<div class="row">
    <div class="panel panel-primary">
        <div class="panel-heading"><h1>@description.HttpMethod.Method @description.RelativePath</h1></div>
        <div class="panel-body"><p>@description.Documentation</p></div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>Request Information</h2>
        </div>
        <div class="panel-body">
            <h3>URI Parameters</h3>
            @Html.DisplayFor(m => m.UriParameters, "Parameters")

            <h3>Body Parameters</h3>

            <p>@Model.RequestDocumentation</p>

            @if (Model.RequestModelDescription != null) {
                @Html.DisplayFor(m => m.RequestModelDescription.ModelType, "ModelDescriptionLink", new {modelDescription = Model.RequestModelDescription})
                if (Model.RequestBodyParameters != null) {
                    @Html.DisplayFor(m => m.RequestBodyParameters, "Parameters")
                }
            } else {
                <p>None.</p>
            }
            @if (Model.SampleRequests.Count > 0) {
                <h3>Request Formats</h3>
                @Html.DisplayFor(m => m.SampleRequests, "Samples")
            }
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>Response Information</h2>
        </div>
        <div class="panel-body">
            <h3>Resource Description</h3>

            <p>@description.ResponseDescription.Documentation</p>

            @if (Model.ResourceDescription != null) {
                @Html.DisplayFor(m => m.ResourceDescription.ModelType, "ModelDescriptionLink", new {modelDescription = Model.ResourceDescription})
                if (Model.ResourceProperties != null) {
                    @Html.DisplayFor(m => m.ResourceProperties, "Parameters")
                }
            } else {
                <p>None.</p>
            }

            @if (Model.SampleResponses.Count > 0) {
                <h3>Response Formats</h3>
                @Html.DisplayFor(m => m.SampleResponses, "Samples")
            }
        </div>
    </div>
</div>

JDMallen.AppName/Views/Help/DisplayTemplates/ImageSample.cshtml
@model JDMallen.AppName.SampleGeneration.ImageSample

<img src="@Model.Src" />

JDMallen.AppName/Views/Help/DisplayTemplates/InvalidSample.cshtml
@model JDMallen.AppName.SampleGeneration.InvalidSample

@if (HttpContext.Current.IsDebuggingEnabled)
{
    <div class="warning-message-container">
        <p>@Model.ErrorMessage</p>
    </div>
}
else
{
    <p>Sample not available.</p>
}

JDMallen.AppName/Views/Help/DisplayTemplates/KeyValuePairModelDescription.cshtml
@model JDMallen.AppName.ModelDescriptions.KeyValuePairModelDescription
Pair of @Html.DisplayFor(m => Model.KeyModelDescription.ModelType, "ModelDescriptionLink", new { modelDescription = Model.KeyModelDescription }) [key]
and @Html.DisplayFor(m => Model.ValueModelDescription.ModelType, "ModelDescriptionLink", new { modelDescription = Model.ValueModelDescription }) [value]

JDMallen.AppName/Views/Help/DisplayTemplates/ModelDescriptionLink.cshtml
@using JDMallen.AppName.ModelDescriptions
@model Type
@{
    ModelDescription modelDescription = ViewBag.modelDescription;
    if (modelDescription is ComplexTypeModelDescription || modelDescription is EnumTypeModelDescription)
    {
        if (Model == typeof(Object))
        {
            @:Object
        }
        else
        {
            @Html.ActionLink(modelDescription.Name, "ResourceModel", "Help", new { modelName = modelDescription.Name }, null)
        }
    }
    else if (modelDescription is CollectionModelDescription)
    {
        var collectionDescription = modelDescription as CollectionModelDescription;
        var elementDescription = collectionDescription.ElementDescription;
        @:Collection of @Html.DisplayFor(m => elementDescription.ModelType, "ModelDescriptionLink", new { modelDescription = elementDescription })
    }
    else
    {
        @Html.DisplayFor(m => modelDescription)
    }
}

JDMallen.AppName/Views/Help/DisplayTemplates/Parameters.cshtml
@using System.Collections.Generic
@using System.Collections.ObjectModel
@using System.Web.Http.Description
@using System.Threading
@using JDMallen.AppName.ModelDescriptions
@model IList<JDMallen.AppName.ModelDescriptions.ParameterDescription>

@if (Model.Count > 0)
{
    <table class="help-page-table">
        <thead>
            <tr><th>Name</th><th>Description</th><th>Type</th><th>Additional information</th></tr>
        </thead>
        <tbody>
            @foreach (ParameterDescription parameter in Model)
            {
                ModelDescription modelDescription = parameter.TypeDescription;
                <tr>
                    <td class="parameter-name">@parameter.Name</td>
                    <td class="parameter-documentation">
                        <p>@parameter.Documentation</p>
                    </td>
                    <td class="parameter-type">
                        @Html.DisplayFor(m => modelDescription.ModelType, "ModelDescriptionLink", new { modelDescription = modelDescription })
                    </td>
                    <td class="parameter-annotations">
                        @if (parameter.Annotations.Count > 0)
                        {
                            foreach (var annotation in parameter.Annotations)
                            {
                                <p>@annotation.Documentation</p>
                            }
                        }
                        else
                        {
                            <p>None.</p>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>None.</p>
}

JDMallen.AppName/Views/Help/DisplayTemplates/Samples.cshtml
@using System.Net.Http.Headers
@model Dictionary<MediaTypeHeaderValue, object>

@{
    // Group the samples into a single tab if they are the same.
    Dictionary<string, object> samples = Model.GroupBy(pair => pair.Value).ToDictionary(
        pair => String.Join(", ", pair.Select(m => m.Key.ToString()).ToArray()), 
        pair => pair.Key);
    var mediaTypes = samples.Keys;
}
<div>
    @foreach (var mediaType in mediaTypes)
    {
        <h4 class="sample-header">@mediaType</h4>
        <div class="sample-content">
            <span><b>Sample:</b></span>
            @{
                var sample = samples[mediaType];
                if (sample == null)
                {
                    <p>Sample not available.</p>
                }
                else
                {
                    @Html.DisplayFor(s => sample);
                }
            }
        </div>
    }
</div>

JDMallen.AppName/Views/Help/DisplayTemplates/SimpleTypeModelDescription.cshtml
@model JDMallen.AppName.ModelDescriptions.SimpleTypeModelDescription
@Model.Documentation

JDMallen.AppName/Views/Help/DisplayTemplates/TextSample.cshtml
@model JDMallen.AppName.SampleGeneration.TextSample

<pre class="wrapped">
@Model.Text
</pre>

JDMallen.AppName/Views/Help/Index.cshtml
@using System.Web.Http
@using System.Web.Http.Controllers
@using System.Web.Http.Description
@using System.Collections.ObjectModel
@model Collection<ApiDescription>

@{
    ViewBag.Title = "Web API Help Page";

    // Group APIs by controller
    ILookup<HttpControllerDescriptor, ApiDescription> apiGroups = Model.ToLookup(api => api.ActionDescriptor.ControllerDescriptor);
}
<div class="row">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h1>@ViewBag.Title</h1>
        </div>
        <div class="panel-body">
            <h2>Hi there!</h2>
            <p>Let's begin!</p>
        </div>
    </div>
    @foreach (var group in apiGroups) {
        @Html.DisplayFor(m => group, "ApiGroup")
    }
</div>

JDMallen.AppName/Views/Help/ResourceModel.cshtml
@using System.Web.Http
@model JDMallen.AppName.ModelDescriptions.ModelDescription

<link type="text/css" href="~/Content/HelpPage.css" rel="stylesheet" />
<div id="body" class="help-page">
    <section class="featured">
        <div class="content-wrapper">
            <p>
                @Html.ActionLink("Help Page Home", "Index")
            </p>
        </div>
    </section>
    <h1>@Model.Name</h1>
    <p>@Model.Documentation</p>
    <section class="content-wrapper main-content clear-fix">
        @Html.DisplayFor(m => Model)
    </section>
</div>

JDMallen.AppName/Views/Index.cshtml
@using System.Net.Http;
@model System.Web.Http.Description.IApiExplorer

<div class="row">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h1>Web API</h1>
        </div>
        <div class="panel-body">
            <p>Hi there!</p>
            <p>Let's begin!</p>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>Users</h3>
        </div>
        <table class="table">
            <thead>
            <tr>
                <th>HTTP Method</th>
                <th>Behavior</th>
            </tr>
            </thead>
                
            <tbody>
            @foreach (var api in Model.ApiDescriptions) {
                <tr>
                    <td><code>@api.HttpMethod&nbsp;@api.RelativePath</code></td>
                    <td>
                        <p>@api.Documentation</p>
                        @foreach (var parameter in api.ParameterDescriptions) {
                            <p>@string.Format("Parameter: {0} - {1}", parameter.Name, parameter.Source)</p>
                        }
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>

JDMallen.AppName/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8" />

    @*Set the viewport width to device width for mobile *@
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewBag.Title - API</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    @Styles.Render("~/Content/bootstrap", "~/Content/site", "~/Content/fontawesome")

    @RenderSection("head", required: false)
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
<div class="container">
    @RenderBody()
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@*Use the Scripts section to define page specific scripts*@
@RenderSection("scripts", required: false)
</body>
</html>